spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=HackathonDB;encrypt=true;trustServerCertificate=true
spring.datasource.username= sa
spring.datasource.password= 12345



spring.jpa.hibernate.ddl-auto=none

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hackathoneventnotif@gmail.com
spring.mail.password=nyirlsqkdvzlojas
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Configuration
app.jwt-secret=mysupersecretkeyformyhackathonsystemjwt2026securekey
app.jwt-access-token-expiration-ms=86400000
app.jwt-refresh-token-expiration-ms=604800000
# CORS Configuration
app.cors.allowed-origins=http://localhost:5173,http://localhost:5174

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=MOCK_ID
spring.security.oauth2.client.registration.google.client-secret=MOCK_SECRET
spring.security.oauth2.client.registration.google.scope=profile, email

# Frontend Redirect URI after successful Google Login
app.oauth2.redirect-uri=http://localhost:5173/oauth2/redirect
